apiVersion: apps/v1
kind: Deployment
metadata:
  name: medium-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medium-app
  template:
    metadata:
      labels:
        app: medium-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: medium-app
              topologyKey: kubernetes.io/hostname
      containers:
      - name: burn
        image: busybox:1.36
        command: ["sh","-c"]
        args: ["while true; do :; done"]
        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"