apiVersion: management.loft.sh/v1
kind: NodeProvider
metadata:
  name: pod-auto-nodes
spec:
  terraform:
    nodeTemplate:
      git:
        repository: https://github.com/loft-demos/vcluster-platform-workshop.git
        subPath: src/tenancy-models/auto-nodes/node
    nodeEnvironmentTemplate:
      infrastructure:
        git:
          repository: https://github.com/loft-demos/vcluster-platform-workshop.git
          subPath: src/tenancy-models/auto-nodes/environment/infrastructure
    nodeTypes:
      - resources:
          cpu: '500m'
          memory: '256Mi'
          pods: '10'
        name: a-small
        metadata: {}
        maxCapacity: 8
      - resources:
          cpu: '750m'
          memory: '512Mi'
          pods: '20'
        name: b-medium
        metadata: {}
        maxCapacity: 4
      - resources:
          cpu: '1'
          memory: 1Gi
          pods: '30'
        name: c-large
        metadata: {}
        maxCapacity: 2
  displayName: Pod Auto Nodes
